using System.IO;
using System.Text;
using DockerManager.App.Models;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace DockerManager.App.Services;

public interface IDockerComposeExporterService
{
    string ExportToComposeYaml(ProfileModel profile);
    bool ExportToFile(ProfileModel profile, string destinationPath, out string? errorMessage);
}

public class DockerComposeExporterService : IDockerComposeExporterService
{
    public string ExportToComposeYaml(ProfileModel profile)
    {
        if (profile == null || profile.Services == null || profile.Services.Count == 0)
        {
            return "services: {}\n";
        }

        var root = new Dictionary<string, object>
        {
            ["name"] = profile.Name.ToLowerInvariant().Replace(" ", "-")
        };

        var servicesDict = new Dictionary<string, object>();
        var namedVolumes = new HashSet<string>();

        foreach (var svc in profile.Services)
        {
            var svcKey = !string.IsNullOrWhiteSpace(svc.Id) ? svc.Id.ToLowerInvariant().Replace(" ", "_") : "service";
            var svcConfig = new Dictionary<string, object>();

            if (!string.IsNullOrWhiteSpace(svc.ContainerName))
            {
                svcConfig["container_name"] = svc.ContainerName;
            }

            if (!string.IsNullOrWhiteSpace(svc.Image))
            {
                svcConfig["image"] = svc.Image;
            }

            if (!string.IsNullOrWhiteSpace(svc.RestartPolicy))
            {
                svcConfig["restart"] = svc.RestartPolicy;
            }

            if (!string.IsNullOrWhiteSpace(svc.NetworkMode))
            {
                svcConfig["network_mode"] = svc.NetworkMode;
            }

            // Ports
            if (svc.Ports != null && svc.Ports.Count > 0)
            {
                var portList = new List<string>();
                foreach (var p in svc.Ports)
                {
                    var proto = string.IsNullOrWhiteSpace(p.Protocol) || p.Protocol.Equals("tcp", StringComparison.OrdinalIgnoreCase)
                        ? ""
                        : $"/{p.Protocol.ToLowerInvariant()}";
                    portList.Add($"{p.HostPort}:{p.ContainerPort}{proto}");
                }
                svcConfig["ports"] = portList;
            }

            // Volumes
            if (svc.Volumes != null && svc.Volumes.Count > 0)
            {
                var volList = new List<string>();
                foreach (var v in svc.Volumes)
                {
                    var host = v.HostPath;
                    if (v.IsNamedVolume)
                    {
                        namedVolumes.Add(host);
                    }
                    var ro = v.ReadOnly ? ":ro" : "";
                    volList.Add($"{host}:{v.ContainerPath}{ro}");
                }
                svcConfig["volumes"] = volList;
            }

            // Environment
            if (svc.Environment != null && svc.Environment.Count > 0)
            {
                var envDict = new Dictionary<string, string>();
                foreach (var kvp in svc.Environment)
                {
                    envDict[kvp.Key] = kvp.Value ?? "";
                }
                svcConfig["environment"] = envDict;
            }

            // Command
            if (svc.Command != null && svc.Command.Count > 0)
            {
                svcConfig["command"] = svc.Command;
            }

            servicesDict[svcKey] = svcConfig;
        }

        root["services"] = servicesDict;

        if (namedVolumes.Count > 0)
        {
            var volumesRoot = new Dictionary<string, object?>();
            foreach (var nv in namedVolumes)
            {
                volumesRoot[nv] = null;
            }
            root["volumes"] = volumesRoot;
        }

        var serializer = new SerializerBuilder()
            .WithNamingConvention(UnderscoredNamingConvention.Instance)
            .Build();

        var yaml = serializer.Serialize(root);

        var header = new StringBuilder();
        header.AppendLine("# Docker Compose file generated by DockerManager");
        header.AppendLine($"# Profile: {profile.Name}");
        if (!string.IsNullOrWhiteSpace(profile.Description))
        {
            header.AppendLine($"# Description: {profile.Description}");
        }
        if (!string.IsNullOrWhiteSpace(profile.Cloudflare?.Domain))
        {
            header.AppendLine($"# Cloudflare Domain: {profile.Cloudflare.Domain}");
        }
        if (!string.IsNullOrWhiteSpace(profile.Registry?.Server) || !string.IsNullOrWhiteSpace(profile.Registry?.Namespace))
        {
            var reg = string.Join("/", new[] { profile.Registry?.Server, profile.Registry?.Namespace }.Where(s => !string.IsNullOrWhiteSpace(s)));
            header.AppendLine($"# Container Registry: {reg}");
        }
        header.AppendLine($"# Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        header.AppendLine();
        header.Append(yaml);

        return header.ToString();
    }

    public bool ExportToFile(ProfileModel profile, string destinationPath, out string? errorMessage)
    {
        errorMessage = null;
        try
        {
            var yaml = ExportToComposeYaml(profile);
            var dir = Path.GetDirectoryName(destinationPath);
            if (!string.IsNullOrWhiteSpace(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }
            File.WriteAllText(destinationPath, yaml, Encoding.UTF8);
            return true;
        }
        catch (Exception ex)
        {
            errorMessage = ex.Message;
            return false;
        }
    }
}